### ISSUE TITLE
refactor: migrate cuelib

### ISSUE THREAD

**Issue by yuyicai** [h8r-dev/cuelib#4]
- ci @vgjm 
  - [x] github
      - [x] test case
- cd @lyzhang1999 
  - [x] argocd
      - [x] test case
- monitoring @lyzhang1999 
  - [x] prometheus
      - [x] test case
  - [x] grafana
      - [x] test case
- logging @lyzhang1999 
  - [x] loki
      - [x] test case 
- dev @yuyicai 
  - [x] nocalhost
      - [x] test case 
- network @lyzhang1999 
  - [x] ingress
    - [x] test case 
- deploy @yuyicai 
  - [x] kubectl
    - [x] test case 
  - [x] helm
    - [x] test case 
- h8r @yuyicai 
  - [x] h8r
    - [x] test case 
- scm @vgjm 
  - [x] github
    - [x] test case 
- utils @yuyicai 
  - [x] random
    - [x] test case 
  - [x] fs
    - [x] test case 
  - [x] base
    - [x] test case

**Comment by lyzhang1999** [comment]
OK, Let's do it.
